### PR TITLE
add fs;ct test;delete reconfig to efuse;

### PR DESCRIPTION
**Pull request by cheerychan**

### CODE REVIEW

**Comment by cheerychan** [comment]
add fs;ct test;delete reconfig to efuse

**Comment by githubclaire** [comment]
rebase and merge

**Comment by githubclaire** [comment]
rebase and merge

**Comment by githubclaire** [comment]
merge new function

**Comment by githubclaire** [comment]
rebase and merge

**Review by githubclaire — APPROVED** [review]

**Comment by githubclaire** [comment]
test merge branch

**Comment by githubclaire** [comment]
can not merge with check error, please send new pull request

**Pull request closed without merging**
